name: Release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build mod
        run: ./gradlew :build --stacktrace

      - name: Publish mod version
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: 45F9B0j8
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 635110
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}

          files-primary: build/libs/!(*-@(dev|sources)).jar
          files-secondary: null

          name: 0.2.1 for MC 1.15 to 1.19
          version: 0.2.1+1.15-1.16
          version-type: release

          loaders: |
            fabric

          dependencies: |
            modmenu       | recommends
